### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [ogawasayaka/child-friendly_hotel#32]
@ogawasayaka 
お疲れ様です！

こちらMVPリリースレビューになります！

### 技術
Googleマップの導入や楽天トラベルAPIなど、外部サービスと連携ができているので技術的なアピールポイントはしっかりある印象を受けました。
以下、技術面でのレビューになります。
- 現時点でCRUD機能がないので何かしら「ユーザーからのアクション」でデータを取るような機能を入れてもいいかと思いました。
- viewファイルにscriotタグを使用してJavascriptを直接書いている箇所がいくつか見受けられるので、リファクタリングの意味もこめて、切り出せるものはJSファイルに切り出してあげても良さそうです。
- 地図から選べるボタンで検索できるかと思うのですが、こちらの機能が動いていなかったので、ご確認をお願いします。

### ユーザビリティ
日本地図やGooglemapを使用して視覚的にユーザーに情報を与えられいるので、使用しやすいアプリケーションの印象を持ちました。
以下、ユーザビリティ面でのレビューになります。
- 楽天トラベルAPIからレビュー内容を取得し、表示していると思いますが、レビューの見せ方を変えて、アプリの世界観を出した方がいいかとおもいました。（表示上で楽天トラベルとの差別化があってもいいかと！）
- 検索の日本地図に表示されている地方のボタンですが、画面が大きくなると、沖縄の下に「関東」のボタンがきてしまうなど、表示が崩れる箇所が何箇所か見受けられたので、レスポンシブ対応をしてあげると良さそうです。（モバイルを想定しているかと思いますが、全てのユーザーがモバイルからアクセスするとは限らないため、最低限整えておいてもいいかと思いました！）
- ハンバーガーメニューが表示したあと、消すことができなかったのでご確認をお願いします。

以上です！

MVPまでの機能は実装できているかと思います！
LGTMです！
（検索機能はもう一つの検索が動いていたので、問題ないかと！）

上記の内容を本リリース実装するタスクに組み込み、スケジュールを立ててみてください。

スケジュール決まりましたら共有をお願いできればと思います。

また上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by ogawasayaka** [comment]
お疲れ様です。
レビューいただきありがとうございます。
以下のとおり対応したいと思います。
レスポンシブ対応があまり上手くいかないのですが、どういった点に気をつけたら良いかや参考になるサイトなどアドバイスなどいただけますと幸いです。
本リリースまでの[issue](https://github.com/users/ogawasayaka/projects/2/views/2)を作成し、リリース予定を5月18日に設定しました。


> ### 技術
> * 現時点でCRUD機能がないので何かしら「ユーザーからのアクション」でデータを取るような機能を入れてもいいかと思いました。

　　**→ ユーザーが宿泊施設の口コミを投稿・削除・編集する機能を本リリースにて実装予定です。**

> * viewファイルにscriotタグを使用してJavascriptを直接書いている箇所がいくつか見受けられるので、リファクタリングの意味もこめて、切り出せるものはJSファイルに切り出してあげても良さそうです。

　　**→ issueにリファクタリングを追加いたします。**

> * 地図から選べるボタンで検索できるかと思うのですが、こちらの機能が動いていなかったので、ご確認をお願いします。
> 
　　**→ 地図から選べるボタンについてですが、こちらは都道府県を選択することのみを目的として作ったものです。
　　　ご指摘いただいたとおり、ユーザーの操作で誤解を与えてしまうような箇所かと思いますので、
　　　「都道府県を選択した時点で検索できる」ような実装をするか、「都道府県を選択したらモーダルを閉じる」・
　　　「最初から都道府県のプルダウンを非表示にしてみる」などの修正を加えたいと思います。**
  
> ### ユーザビリティ

> * 楽天トラベルAPIからレビュー内容を取得し、表示していると思いますが、レビューの見せ方を変えて、アプリの世界観を出した方がいいかとおもいました。（表示上で楽天トラベルとの差別化があってもいいかと！）

　　**→　難しいですが、いろんなサイトを参考に挑戦してみます...!**

> * 検索の日本地図に表示されている地方のボタンですが、画面が大きくなると、沖縄の下に「関東」のボタンがきてしまうなど、表示が崩れる箇所が何箇所か見受けられたので、レスポンシブ対応をしてあげると良さそうです。（モバイルを想定しているかと思いますが、全てのユーザーがモバイルからアクセスするとは限らないため、最低限整えておいてもいいかと思いました！）

       **→  こちらのレスポンシブ対応に挑戦していたのですが、上手くいかなかったため、再度挑戦したいです。**

> * ハンバーガーメニューが表示したあと、消すことができなかったのでご確認をお願いします。
> 
　　**→ 調整いたします。**

**Comment by tmtkzk0823** [comment]
> リリース予定を5月18日に設定しました。

承知しました！
ありがとうございます！

> レスポンシブ対応があまり上手くいかないのですが、どういった点に気をつけたら良いかや参考になるサイトなどアドバイスなどいただけますと幸いです。

tailwindを使用していると、よしなにレスポンシブ対応をしてくれると思いますが、念の為PCの画面でも、モバイルのバランスで表示される様に、screen()などを使用して、上下のスペースなどを調整するのが良さそうかと思いました！
https://zenn.dev/amon/articles/9e8b7d220d2661

**Comment by ogawasayaka** [comment]
関数 screen()があるんですね！教えていただきありがとうございました。
